changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

checksumBehavior: 'update'

defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.26.cjs
# httpProxy: http://127.0.0.1:7890
# httpsProxy: http://127.0.0.1:7890
