---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teable.nameBuilder" (list $ "backend") }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  jwt-secret: {{ .Values.config.jwt.secret | default (randAlphaNum 64) | quote }}
  session-secret: {{ .Values.config.session.secret | default (randAlphaNum 64) | quote }}
  secretKey: {{ .Values.config.secretKey | default (randAlphaNum 64) | quote }}
  accessToken-encryption-key: {{ .Values.config.accessToken.encryption.key | default (randAlphaNum 64) | quote }}
  accessToken-encryption-iv: {{ .Values.config.accessToken.encryption.iv | default (randAlphaNum 64) | quote }}

  mail-host: {{.Values.config.mail.host | quote}}
  mail-port: {{.Values.config.mail.port | quote}}
  mail-secure: {{.Values.config.mail.secure | quote}}
  mail-sender: {{.Values.config.mail.sender | quote}}
  mail-sender-name: {{.Values.config.mail.senderName | quote}}
  mail-auth-username: {{.Values.config.mail.auth.username | quote}}
  mail-auth-password: {{.Values.config.mail.auth.password | quote}}

  storage-provider: {{ .Values.config.storage.provider | quote }}
  storage-publicBucket: {{ .Values.config.storage.publicBucket | quote }}
  storage-privateBucket: {{ .Values.config.storage.privateBucket | quote }}
  storage-minio-endPoint: {{ .Values.config.storage.minio.endPoint | quote }}
  storage-minio-port: {{ .Values.config.storage.minio.port | quote }}
  storage-minio-useSSL: {{ .Values.config.storage.minio.useSSL | quote }}
  storage-minio-accessKey: {{ .Values.config.storage.minio.accessKey | quote }}
  storage-minio-secretKey: {{ .Values.config.storage.minio.secretKey | quote }}
