{{- $envVars := include "common.env.transformDict" .Values.envVars -}}
{{- $root := .Values.migrationJob }}
{{- if $root.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "teable.nameBuilder" (list $ "migration") }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/part: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "teable.nameBuilder" (list $ "migration") }}
      {{- with $root.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/part: migration
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          {{- include "teable.shared.image" (list $ "migrationJob") | nindent 10 }}
          env:
            {{- include "teable.env.shared" $ | nindent 12 }}
            {{- $envVars | indent 12 }}
          resources:
            {{- toYaml $root.resources | nindent 12 }}
{{- end }}
