{{- define "teable.dictToQueryString" -}}
    {{- if (eq (typeOf .) "string") -}}
        {{- . -}}
    {{- else -}}
        {{- $first := true -}}
        {{ range $key, $value := . -}}
          {{- if $first -}}
            {{- $first = false -}}
          {{- else -}}
            &
          {{- end -}}
          {{- $key | urlquery }}={{ $value | urlquery -}}
        {{- end -}}
    {{- end -}}
{{- end -}}

{{- define "teable.safe_url" -}}
{{- urlJoin (
    dict
        "scheme" .scheme
        "userinfo" (printf "%s:%s" (urlquery .user)  (urlquery .password) )
        "host" (printf "%s:%s" .host (.port | print))
        "name" (printf "/%s" .path)
        "query" (include "teable.dictToQueryString" (.query | default (dict)))
    )
-}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teable.nameBuilder" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.config.jwtSecret | default (randAlphaNum 64) | quote }}
  session-secret: {{ .Values.config.jwtSecret | default (randAlphaNum 64) | quote }}
  accessToken-encryption-key: {{ .Values.config.accessToken.key | default (randAlphaNum 16) | quote }}
  accessToken-encryption-iv: {{ .Values.config.accessToken.iv | default (randAlphaNum 16) | quote }}
  {{- if .Values.config.mail.host }}
  mail-auth-password: {{ .Values.config.mail.auth.password | quote }}
  {{- end }}
