version: '3.9'

services:
  teable:
    image: ghcr.io/teableio/teable:latest
    deploy:
      replicas: 2
    restart: always
    expose:
      - '3000'
    volumes:
      - teable_data:/app/.assets:rw
    environment:
      - TZ=${TIMEZONE}
      - NODE_OPTIONS=--max-old-space-size=1024
      - PUBLIC_ORIGIN=http://127.0.0.1
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}
      - BACKEND_CACHE_PROVIDER=redis
      - BACKEND_CACHE_REDIS_URI=redis://:${POSTGRES_PASSWORD}@teable_cache:6379/0
    networks:
      - teable-cluster
    depends_on:
      teable_db_migrate:
        condition: service_completed_successfully
      teable_cache:
        condition: service_healthy

  teable_db:
    image: postgres:15.4
    restart: always
    expose:
      - '5432'
    volumes:
      - teable_db:/var/lib/postgresql/data:rw
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - teable-cluster
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  teable_cache:
    image: redis:7.2.4
    restart: always
    expose:
      - '6379'
    volumes:
      - teable_cache:/data:rw
    networks:
      - teable-cluster
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

  teable_db_migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - TZ=${TIMEZONE}
      - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}
    networks:
      - teable-cluster
    depends_on:
      teable_db:
        condition: service_healthy

  teable_reverse_proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - teable-cluster
    depends_on:
      teable:
        condition: service_started

networks:
  teable-cluster:
    name: teable_cluster_network
    driver: bridge

volumes:
  teable_data: {}
  teable_db: {}
  teable_cache: {}
