name: Build and Push to Alibaba Cloud Registry

on:
  push:
    branches:
      - main
      - fix/polish-table # todo: delete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Alibaba Cloud Docker Registry
        run: docker login --username=${{ secrets.ALI_DOCKER_USERNAME }} registry.cn-beijing.aliyuncs.com --password=${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.cn-beijing.aliyuncs.com/bieber/teable:${GITHUB_SHA} -f dockers/teable/Dockerfile .
          docker push registry.cn-beijing.aliyuncs.com/bieber/teable:${GITHUB_SHA}
