name: Build and Push to Docker Registry

on:
  push:
    branches:
      - develop
      - chore/upgrade

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [app, db-migrate]
        include:
          - target: app
            file: Dockerfile
            image: teable
          - target: db-migrate
            file: Dockerfile.db-migrate
            image: teable-db-migrate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_KEY }}

      - name: Login to Ali container registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Install zx
        run: npm install -g zx

      - name: ⚙️ Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ inputs.push-images }}
          # generate Docker tags based on the following events/attributes
          tags: ${{ inputs.push-tags }}
      - name: 📦 Build and push
        run: |
          zx scripts/build-image.mjs --file=dockers/teable/${{ matrix.file }} \
              --cache-from=type=registry,ref=ghcr.io/teableio/${{ matrix.image }}:buildcache \
              --cache-to=type=registry,ref=ghcr.io/teableio/${{ matrix.image }}:buildcache,mode=max \
              --tag=${{ steps.meta.outputs.tags }} \
              --push
