name: Integration Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Integration Tests

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        database-type: [postgres, sqlite]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Start Database(s)
        run: |
          docker-compose \
            --file "dockers/docker-compose.integration-test.yml" \
            up \
              --detach \
              --build \
              "${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite'

      - name: Run yarn install
        run: yarn install

      - name: Initialize Database(s)
        run: |
          docker-compose \
            --file "dockers/docker-compose.integration-test.yml" \
            up \
              "wait${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite'

      - name: Run build
        run: |
          yarn g:build
          yarn workspace @teable-group/db-main-prisma db:${{ matrix.database-type }}:push

      - name: Run Tests
        run: |
          yarn workspace @teable-group/nestjs-backend test:${{ matrix.database-type }}:db

      - name: Stop Database(s)
        run: |
          docker-compose \
            --file "dockers/docker-compose.integration-test.yml" \
            down
        if: matrix.database-type != 'sqlite'
