name: Integration Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Integration Tests

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        database-type: [postgres, sqlite]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Initialize Database(s)
        run: |
          make db-${{ matrix.database-type }}
        if: matrix.database-type != 'sqlite'

      - name: Run yarn install
        run: yarn install

      - name: Run build
        run: |
          yarn g:build

      - name: Run Tests
        run: |
          yarn workspace @teable-group/nestjs-backend test:${{ matrix.database-type }}:db

      - name: Stop Database(s)
        run: |
          make docker.down
        if: matrix.database-type != 'sqlite'
