name: Integration Tests

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'apps/nestjs-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Integration Tests

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.9.0]
        database-type: [postgres, sqlite]
    env:
      CI: 1

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: 🧪 Run Tests
        env:
          CI: 1
          VITEST_MAX_THREADS: 2
          VITEST_MIN_THREADS: 1
        run: |
          make ${{ matrix.database-type }}.integration.test
