name: Linting and Types

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linting and Types

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Run yarn install
        run: yarn install

      - name: Run build
        run: |
          yarn g:build

      - name: Typecheck
        run: |
          yarn g:typecheck

      - name: Linter
        run: |
          yarn g:lint:everything
