name: Unit Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Tests

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: 🧩 Generate Prisma Client
        working-directory: packages/db-main-prisma
        run: |
          yarn workspace @teable-group/db-main-prisma prisma-generate --schema ./prisma/postgres/schema.prisma

      - name: 🏗 Run build
        run: |
          yarn workspaces foreach -A -tv --exclude '@teable-group/(app|backend)' run build

      - name: 🧪 Run Tests
        run: |
          yarn workspaces foreach -A -tv --include '@teable-group/*' run test-unit
